# Generated by Django 3.2 on 2024-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('number', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('band_name', models.CharField(max_length=50)),
            ],
        ),
    ]
